// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ProjectionRouterTop5,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=2.777778,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.524250,HLS_SYN_LAT=108,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=667,HLS_SYN_LUT=2172,HLS_VERSION=2018_2}" *)

module ProjectionRouterTop5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        proj1in_dataarray_data_V_address0,
        proj1in_dataarray_data_V_ce0,
        proj1in_dataarray_data_V_q0,
        proj1in_nentries_0_V,
        proj1in_nentries_1_V,
        proj2in_dataarray_data_V_address0,
        proj2in_dataarray_data_V_ce0,
        proj2in_dataarray_data_V_q0,
        proj2in_nentries_0_V,
        proj2in_nentries_1_V,
        proj3in_dataarray_data_V_address0,
        proj3in_dataarray_data_V_ce0,
        proj3in_dataarray_data_V_q0,
        proj3in_nentries_0_V,
        proj3in_nentries_1_V,
        proj4in_dataarray_data_V_address0,
        proj4in_dataarray_data_V_ce0,
        proj4in_dataarray_data_V_q0,
        proj4in_nentries_0_V,
        proj4in_nentries_1_V,
        proj5in_dataarray_data_V_address0,
        proj5in_dataarray_data_V_ce0,
        proj5in_dataarray_data_V_q0,
        proj5in_nentries_0_V,
        proj5in_nentries_1_V,
        bx_o_V,
        bx_o_V_ap_vld,
        allprojout_dataarray_data_V_address0,
        allprojout_dataarray_data_V_ce0,
        allprojout_dataarray_data_V_we0,
        allprojout_dataarray_data_V_d0,
        allprojout_nentries_0_V,
        allprojout_nentries_0_V_ap_vld,
        allprojout_nentries_1_V,
        allprojout_nentries_1_V_ap_vld,
        allprojout_nentries_2_V,
        allprojout_nentries_2_V_ap_vld,
        allprojout_nentries_3_V,
        allprojout_nentries_3_V_ap_vld,
        allprojout_nentries_4_V,
        allprojout_nentries_4_V_ap_vld,
        allprojout_nentries_5_V,
        allprojout_nentries_5_V_ap_vld,
        allprojout_nentries_6_V,
        allprojout_nentries_6_V_ap_vld,
        allprojout_nentries_7_V,
        allprojout_nentries_7_V_ap_vld,
        vmprojout1_dataarray_data_V_address0,
        vmprojout1_dataarray_data_V_ce0,
        vmprojout1_dataarray_data_V_we0,
        vmprojout1_dataarray_data_V_d0,
        vmprojout1_nentries_0_V,
        vmprojout1_nentries_0_V_ap_vld,
        vmprojout1_nentries_1_V,
        vmprojout1_nentries_1_V_ap_vld,
        vmprojout2_dataarray_data_V_address0,
        vmprojout2_dataarray_data_V_ce0,
        vmprojout2_dataarray_data_V_we0,
        vmprojout2_dataarray_data_V_d0,
        vmprojout2_nentries_0_V,
        vmprojout2_nentries_0_V_ap_vld,
        vmprojout2_nentries_1_V,
        vmprojout2_nentries_1_V_ap_vld,
        vmprojout3_dataarray_data_V_address0,
        vmprojout3_dataarray_data_V_ce0,
        vmprojout3_dataarray_data_V_we0,
        vmprojout3_dataarray_data_V_d0,
        vmprojout3_nentries_0_V,
        vmprojout3_nentries_0_V_ap_vld,
        vmprojout3_nentries_1_V,
        vmprojout3_nentries_1_V_ap_vld,
        vmprojout4_dataarray_data_V_address0,
        vmprojout4_dataarray_data_V_ce0,
        vmprojout4_dataarray_data_V_we0,
        vmprojout4_dataarray_data_V_d0,
        vmprojout4_nentries_0_V,
        vmprojout4_nentries_0_V_ap_vld,
        vmprojout4_nentries_1_V,
        vmprojout4_nentries_1_V_ap_vld,
        vmprojout5_dataarray_data_V_address0,
        vmprojout5_dataarray_data_V_ce0,
        vmprojout5_dataarray_data_V_we0,
        vmprojout5_dataarray_data_V_d0,
        vmprojout5_nentries_0_V,
        vmprojout5_nentries_0_V_ap_vld,
        vmprojout5_nentries_1_V,
        vmprojout5_nentries_1_V_ap_vld,
        vmprojout6_dataarray_data_V_address0,
        vmprojout6_dataarray_data_V_ce0,
        vmprojout6_dataarray_data_V_we0,
        vmprojout6_dataarray_data_V_d0,
        vmprojout6_nentries_0_V,
        vmprojout6_nentries_0_V_ap_vld,
        vmprojout6_nentries_1_V,
        vmprojout6_nentries_1_V_ap_vld,
        vmprojout7_dataarray_data_V_address0,
        vmprojout7_dataarray_data_V_ce0,
        vmprojout7_dataarray_data_V_we0,
        vmprojout7_dataarray_data_V_d0,
        vmprojout7_nentries_0_V,
        vmprojout7_nentries_0_V_ap_vld,
        vmprojout7_nentries_1_V,
        vmprojout7_nentries_1_V_ap_vld,
        vmprojout8_dataarray_data_V_address0,
        vmprojout8_dataarray_data_V_ce0,
        vmprojout8_dataarray_data_V_we0,
        vmprojout8_dataarray_data_V_d0,
        vmprojout8_nentries_0_V,
        vmprojout8_nentries_0_V_ap_vld,
        vmprojout8_nentries_1_V,
        vmprojout8_nentries_1_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [7:0] proj1in_dataarray_data_V_address0;
output   proj1in_dataarray_data_V_ce0;
input  [59:0] proj1in_dataarray_data_V_q0;
input  [7:0] proj1in_nentries_0_V;
input  [7:0] proj1in_nentries_1_V;
output  [7:0] proj2in_dataarray_data_V_address0;
output   proj2in_dataarray_data_V_ce0;
input  [59:0] proj2in_dataarray_data_V_q0;
input  [7:0] proj2in_nentries_0_V;
input  [7:0] proj2in_nentries_1_V;
output  [7:0] proj3in_dataarray_data_V_address0;
output   proj3in_dataarray_data_V_ce0;
input  [59:0] proj3in_dataarray_data_V_q0;
input  [7:0] proj3in_nentries_0_V;
input  [7:0] proj3in_nentries_1_V;
output  [7:0] proj4in_dataarray_data_V_address0;
output   proj4in_dataarray_data_V_ce0;
input  [59:0] proj4in_dataarray_data_V_q0;
input  [7:0] proj4in_nentries_0_V;
input  [7:0] proj4in_nentries_1_V;
output  [7:0] proj5in_dataarray_data_V_address0;
output   proj5in_dataarray_data_V_ce0;
input  [59:0] proj5in_dataarray_data_V_q0;
input  [7:0] proj5in_nentries_0_V;
input  [7:0] proj5in_nentries_1_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [9:0] allprojout_dataarray_data_V_address0;
output   allprojout_dataarray_data_V_ce0;
output   allprojout_dataarray_data_V_we0;
output  [59:0] allprojout_dataarray_data_V_d0;
output  [7:0] allprojout_nentries_0_V;
output   allprojout_nentries_0_V_ap_vld;
output  [7:0] allprojout_nentries_1_V;
output   allprojout_nentries_1_V_ap_vld;
output  [7:0] allprojout_nentries_2_V;
output   allprojout_nentries_2_V_ap_vld;
output  [7:0] allprojout_nentries_3_V;
output   allprojout_nentries_3_V_ap_vld;
output  [7:0] allprojout_nentries_4_V;
output   allprojout_nentries_4_V_ap_vld;
output  [7:0] allprojout_nentries_5_V;
output   allprojout_nentries_5_V_ap_vld;
output  [7:0] allprojout_nentries_6_V;
output   allprojout_nentries_6_V_ap_vld;
output  [7:0] allprojout_nentries_7_V;
output   allprojout_nentries_7_V_ap_vld;
output  [7:0] vmprojout1_dataarray_data_V_address0;
output   vmprojout1_dataarray_data_V_ce0;
output   vmprojout1_dataarray_data_V_we0;
output  [20:0] vmprojout1_dataarray_data_V_d0;
output  [7:0] vmprojout1_nentries_0_V;
output   vmprojout1_nentries_0_V_ap_vld;
output  [7:0] vmprojout1_nentries_1_V;
output   vmprojout1_nentries_1_V_ap_vld;
output  [7:0] vmprojout2_dataarray_data_V_address0;
output   vmprojout2_dataarray_data_V_ce0;
output   vmprojout2_dataarray_data_V_we0;
output  [20:0] vmprojout2_dataarray_data_V_d0;
output  [7:0] vmprojout2_nentries_0_V;
output   vmprojout2_nentries_0_V_ap_vld;
output  [7:0] vmprojout2_nentries_1_V;
output   vmprojout2_nentries_1_V_ap_vld;
output  [7:0] vmprojout3_dataarray_data_V_address0;
output   vmprojout3_dataarray_data_V_ce0;
output   vmprojout3_dataarray_data_V_we0;
output  [20:0] vmprojout3_dataarray_data_V_d0;
output  [7:0] vmprojout3_nentries_0_V;
output   vmprojout3_nentries_0_V_ap_vld;
output  [7:0] vmprojout3_nentries_1_V;
output   vmprojout3_nentries_1_V_ap_vld;
output  [7:0] vmprojout4_dataarray_data_V_address0;
output   vmprojout4_dataarray_data_V_ce0;
output   vmprojout4_dataarray_data_V_we0;
output  [20:0] vmprojout4_dataarray_data_V_d0;
output  [7:0] vmprojout4_nentries_0_V;
output   vmprojout4_nentries_0_V_ap_vld;
output  [7:0] vmprojout4_nentries_1_V;
output   vmprojout4_nentries_1_V_ap_vld;
output  [7:0] vmprojout5_dataarray_data_V_address0;
output   vmprojout5_dataarray_data_V_ce0;
output   vmprojout5_dataarray_data_V_we0;
output  [20:0] vmprojout5_dataarray_data_V_d0;
output  [7:0] vmprojout5_nentries_0_V;
output   vmprojout5_nentries_0_V_ap_vld;
output  [7:0] vmprojout5_nentries_1_V;
output   vmprojout5_nentries_1_V_ap_vld;
output  [7:0] vmprojout6_dataarray_data_V_address0;
output   vmprojout6_dataarray_data_V_ce0;
output   vmprojout6_dataarray_data_V_we0;
output  [20:0] vmprojout6_dataarray_data_V_d0;
output  [7:0] vmprojout6_nentries_0_V;
output   vmprojout6_nentries_0_V_ap_vld;
output  [7:0] vmprojout6_nentries_1_V;
output   vmprojout6_nentries_1_V_ap_vld;
output  [7:0] vmprojout7_dataarray_data_V_address0;
output   vmprojout7_dataarray_data_V_ce0;
output   vmprojout7_dataarray_data_V_we0;
output  [20:0] vmprojout7_dataarray_data_V_d0;
output  [7:0] vmprojout7_nentries_0_V;
output   vmprojout7_nentries_0_V_ap_vld;
output  [7:0] vmprojout7_nentries_1_V;
output   vmprojout7_nentries_1_V_ap_vld;
output  [7:0] vmprojout8_dataarray_data_V_address0;
output   vmprojout8_dataarray_data_V_ce0;
output   vmprojout8_dataarray_data_V_we0;
output  [20:0] vmprojout8_dataarray_data_V_d0;
output  [7:0] vmprojout8_nentries_0_V;
output   vmprojout8_nentries_0_V_ap_vld;
output  [7:0] vmprojout8_nentries_1_V;
output   vmprojout8_nentries_1_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg proj1in_dataarray_data_V_ce0;
reg proj2in_dataarray_data_V_ce0;
reg proj3in_dataarray_data_V_ce0;
reg proj4in_dataarray_data_V_ce0;
reg proj5in_dataarray_data_V_ce0;
reg allprojout_dataarray_data_V_ce0;
reg allprojout_dataarray_data_V_we0;
reg[7:0] allprojout_nentries_0_V;
reg allprojout_nentries_0_V_ap_vld;
reg[7:0] allprojout_nentries_1_V;
reg allprojout_nentries_1_V_ap_vld;
reg[7:0] allprojout_nentries_2_V;
reg allprojout_nentries_2_V_ap_vld;
reg[7:0] allprojout_nentries_3_V;
reg allprojout_nentries_3_V_ap_vld;
reg[7:0] allprojout_nentries_4_V;
reg allprojout_nentries_4_V_ap_vld;
reg[7:0] allprojout_nentries_5_V;
reg allprojout_nentries_5_V_ap_vld;
reg[7:0] allprojout_nentries_6_V;
reg allprojout_nentries_6_V_ap_vld;
reg[7:0] allprojout_nentries_7_V;
reg allprojout_nentries_7_V_ap_vld;
reg vmprojout1_dataarray_data_V_ce0;
reg vmprojout1_dataarray_data_V_we0;
reg[7:0] vmprojout1_nentries_0_V;
reg vmprojout1_nentries_0_V_ap_vld;
reg[7:0] vmprojout1_nentries_1_V;
reg vmprojout1_nentries_1_V_ap_vld;
reg vmprojout2_dataarray_data_V_ce0;
reg vmprojout2_dataarray_data_V_we0;
reg[7:0] vmprojout2_nentries_0_V;
reg vmprojout2_nentries_0_V_ap_vld;
reg[7:0] vmprojout2_nentries_1_V;
reg vmprojout2_nentries_1_V_ap_vld;
reg vmprojout3_dataarray_data_V_ce0;
reg vmprojout3_dataarray_data_V_we0;
reg[7:0] vmprojout3_nentries_0_V;
reg vmprojout3_nentries_0_V_ap_vld;
reg[7:0] vmprojout3_nentries_1_V;
reg vmprojout3_nentries_1_V_ap_vld;
reg vmprojout4_dataarray_data_V_ce0;
reg vmprojout4_dataarray_data_V_we0;
reg[7:0] vmprojout4_nentries_0_V;
reg vmprojout4_nentries_0_V_ap_vld;
reg[7:0] vmprojout4_nentries_1_V;
reg vmprojout4_nentries_1_V_ap_vld;
reg vmprojout5_dataarray_data_V_ce0;
reg vmprojout5_dataarray_data_V_we0;
reg[7:0] vmprojout5_nentries_0_V;
reg vmprojout5_nentries_0_V_ap_vld;
reg[7:0] vmprojout5_nentries_1_V;
reg vmprojout5_nentries_1_V_ap_vld;
reg vmprojout6_dataarray_data_V_ce0;
reg vmprojout6_dataarray_data_V_we0;
reg[7:0] vmprojout6_nentries_0_V;
reg vmprojout6_nentries_0_V_ap_vld;
reg[7:0] vmprojout6_nentries_1_V;
reg vmprojout6_nentries_1_V_ap_vld;
reg vmprojout7_dataarray_data_V_ce0;
reg vmprojout7_dataarray_data_V_we0;
reg[7:0] vmprojout7_nentries_0_V;
reg vmprojout7_nentries_0_V_ap_vld;
reg[7:0] vmprojout7_nentries_1_V;
reg vmprojout7_nentries_1_V_ap_vld;
reg vmprojout8_dataarray_data_V_ce0;
reg vmprojout8_dataarray_data_V_we0;
reg[7:0] vmprojout8_nentries_0_V;
reg vmprojout8_nentries_0_V_ap_vld;
reg[7:0] vmprojout8_nentries_1_V;
reg vmprojout8_nentries_1_V_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
reg    bx_o_V_1_ack_in;
reg   [6:0] p_Repl2_3_reg_755;
reg   [6:0] p_Repl2_3_reg_755_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] p_Repl2_3_reg_755_pp0_iter2_reg;
reg   [6:0] p_Repl2_3_reg_755_pp0_iter3_reg;
wire   [2:0] bx_V_read_read_fu_308_p2;
wire   [11:0] tmp_2_cast_fu_775_p1;
reg   [11:0] tmp_2_cast_reg_1892;
wire   [0:0] tmp_2_fu_779_p1;
reg   [0:0] tmp_2_reg_1897;
wire   [9:0] tmp_15_cast_fu_791_p1;
reg   [9:0] tmp_15_cast_reg_1903;
wire   [7:0] numbersin_0_V_fu_795_p3;
reg   [7:0] numbersin_0_V_reg_2001;
wire   [0:0] p_Val2_s_fu_803_p2;
reg   [0:0] p_Val2_s_reg_2006;
wire   [7:0] numbersin_1_V_fu_809_p3;
reg   [7:0] numbersin_1_V_reg_2012;
wire   [0:0] tmp_4_fu_817_p2;
reg   [0:0] tmp_4_reg_2017;
wire   [7:0] numbersin_2_V_fu_823_p3;
reg   [7:0] numbersin_2_V_reg_2022;
wire   [0:0] tmp_5_fu_831_p2;
reg   [0:0] tmp_5_reg_2027;
wire   [7:0] numbersin_3_V_fu_837_p3;
reg   [7:0] numbersin_3_V_reg_2032;
wire   [7:0] numbersin_4_V_fu_958_p3;
reg   [7:0] numbersin_4_V_reg_2038;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_8_fu_994_p2;
reg   [0:0] tmp_8_reg_2043;
wire   [6:0] i_fu_1000_p2;
reg   [6:0] i_reg_2047;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_9_fu_1009_p2;
reg   [0:0] tmp_9_reg_2052;
reg   [0:0] tmp_9_reg_2052_pp0_iter1_reg;
reg   [0:0] tmp_9_reg_2052_pp0_iter2_reg;
reg   [0:0] tmp_9_reg_2052_pp0_iter3_reg;
wire   [4:0] read_imem_V_fu_1030_p1;
reg   [4:0] read_imem_V_reg_2056;
wire   [0:0] tmp_56_fu_1121_p2;
wire   [0:0] tmp_i_fu_1127_p2;
reg   [0:0] tmp_i_reg_2094;
wire   [0:0] tmp_i1_i_fu_1132_p2;
reg   [0:0] tmp_i1_i_reg_2099;
wire   [0:0] tmp_i1_i_i_fu_1137_p2;
reg   [0:0] tmp_i1_i_i_reg_2104;
wire   [0:0] tmp_i1_i_i_i_fu_1142_p2;
reg   [0:0] tmp_i1_i_i_i_reg_2109;
wire   [0:0] tmp_i2_i_fu_1147_p2;
reg   [0:0] tmp_i2_i_reg_2114;
wire   [59:0] p_Val2_5_fu_1180_p3;
reg   [59:0] p_Val2_5_reg_2119;
reg   [2:0] iphi_V_reg_2124;
reg   [2:0] iphi_V_reg_2124_pp0_iter3_reg;
reg   [4:0] tmp_14_reg_2128;
reg   [3:0] phitmp718_i_reg_2133;
reg   [3:0] phitmp718_i_reg_2133_pp0_iter3_reg;
reg   [4:0] phitmp708_i_reg_2138;
reg   [4:0] phitmp708_i_reg_2138_pp0_iter3_reg;
wire   [0:0] psseed_fu_1273_p2;
reg   [0:0] psseed_reg_2143;
reg   [0:0] psseed_reg_2143_pp0_iter3_reg;
wire   [12:0] r_V_2_fu_1318_p2;
reg   [12:0] r_V_2_reg_2148;
reg   [3:0] phitmp716_i_reg_2153;
wire   [2:0] zbin1_V_fu_1348_p3;
reg   [2:0] zbin1_V_reg_2158;
wire   [0:0] tmp_38_fu_1356_p1;
reg   [0:0] tmp_38_reg_2164;
wire   [0:0] tmp_53_fu_1363_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [6:0] ap_phi_mux_p_Repl2_3_phi_fu_759_p4;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_17_fu_1041_p1;
wire  signed [63:0] tmp_63_cast_fu_1378_p1;
wire  signed [63:0] tmp_62_cast_fu_1513_p1;
wire   [0:0] tmp_31_fu_1498_p2;
wire  signed [63:0] tmp_61_cast_fu_1562_p1;
wire   [0:0] tmp_30_fu_1547_p2;
wire  signed [63:0] tmp_60_cast_fu_1611_p1;
wire   [0:0] tmp_29_fu_1596_p2;
wire  signed [63:0] tmp_59_cast_fu_1660_p1;
wire   [0:0] tmp_28_fu_1645_p2;
wire  signed [63:0] tmp_58_cast_fu_1709_p1;
wire   [0:0] tmp_27_fu_1694_p2;
wire  signed [63:0] tmp_57_cast_fu_1758_p1;
wire   [0:0] tmp_26_fu_1743_p2;
wire  signed [63:0] tmp_39_cast_fu_1807_p1;
wire   [0:0] tmp_25_fu_1792_p2;
wire  signed [63:0] tmp_36_cast_fu_1856_p1;
wire   [0:0] tmp_24_fu_1841_p2;
reg   [31:0] addr_index_assign_7_fu_264;
wire   [31:0] nvmprojout8_fu_1533_p2;
reg   [31:0] addr_index_assign_6_fu_268;
wire   [31:0] nvmprojout7_fu_1582_p2;
reg   [31:0] addr_index_assign_5_fu_272;
wire   [31:0] nvmprojout6_fu_1631_p2;
reg   [31:0] addr_index_assign_4_fu_276;
wire   [31:0] nvmprojout5_fu_1680_p2;
reg   [31:0] addr_index_assign_3_fu_280;
wire   [31:0] nvmprojout4_fu_1729_p2;
reg   [31:0] addr_index_assign_2_fu_284;
wire   [31:0] nvmprojout3_fu_1778_p2;
reg   [31:0] addr_index_assign_1_fu_288;
wire   [31:0] nvmprojout2_fu_1827_p2;
reg   [31:0] addr_index_assign_fu_292;
wire   [31:0] nvmprojout1_fu_1876_p2;
reg   [31:0] addr_index_assign_8_fu_296;
wire   [31:0] nallproj_fu_1404_p2;
reg   [4:0] p_Val2_4_fu_300;
wire   [4:0] p_Val2_4_ph_fu_981_p3;
wire   [4:0] mem_hasdata_V_4_fu_1103_p3;
reg   [6:0] read_addr_V_read_assign_fu_304;
wire   [6:0] mem_read_addr_V_1_fu_1095_p3;
wire   [7:0] p_09_0_i76_i_fu_1387_p2;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] p_09_0_i_i_fu_1865_p2;
wire   [7:0] p_09_0_i35_i_fu_1816_p2;
wire   [7:0] p_09_0_i41_i_fu_1767_p2;
wire   [7:0] p_09_0_i47_i_fu_1718_p2;
wire   [7:0] p_09_0_i53_i_fu_1669_p2;
wire   [7:0] p_09_0_i59_i_fu_1620_p2;
wire   [7:0] p_09_0_i65_i_fu_1571_p2;
wire   [7:0] p_09_0_i71_i_fu_1522_p2;
wire   [20:0] ret_V_fu_1473_p7;
wire   [9:0] tmp_fu_767_p3;
wire   [7:0] tmp_12_fu_783_p3;
wire   [1:0] p_Val2_cast_cast_fu_895_p1;
wire   [1:0] tmp_3_fu_898_p3;
wire   [1:0] p_Val2_1_fu_905_p3;
wire   [2:0] tmp_13_fu_916_p3;
wire   [4:0] p_Val2_1_cast_fu_912_p1;
wire   [4:0] p_Result_s_fu_924_p1;
wire   [4:0] p_Val2_2_fu_928_p3;
wire   [0:0] tmp_6_fu_935_p2;
reg   [4:0] p_Result_1_fu_940_p4;
wire   [4:0] p_Val2_3_fu_950_p3;
wire   [0:0] tmp_7_fu_965_p2;
reg   [4:0] p_Result_2_fu_971_p4;
wire   [31:0] tmp_s_fu_1018_p1;
reg   [31:0] val_assign_fu_1022_p3;
wire   [7:0] tmp_15_fu_1034_p3;
wire   [6:0] mem_read_addr_V_fu_1050_p2;
wire   [2:0] tmp_10_fu_1064_p6;
wire   [7:0] tmp_11_cast_fu_1056_p1;
wire   [7:0] tmp_10_fu_1064_p7;
wire   [31:0] i_assign_fu_1081_p1;
wire   [0:0] tmp_11_fu_1075_p2;
reg   [4:0] p_Result_3_fu_1085_p4;
wire   [59:0] data_data_V_read_assign_fu_1152_p3;
wire   [59:0] data_data_V_read_assign_1_fu_1159_p3;
wire   [59:0] data_data_V_read_assign_2_fu_1166_p3;
wire   [59:0] data_data_V_read_assign_3_fu_1173_p3;
wire   [9:0] tmp_22_fu_1217_p4;
wire   [10:0] p_shl_fu_1227_p3;
wire   [10:0] irinv_tmp_V_fu_1235_p2;
wire   [2:0] iseed_V_fu_1251_p4;
wire   [0:0] phitmp712_i_fu_1261_p2;
wire   [0:0] not_i_fu_1267_p2;
wire  signed [11:0] r_V_fu_1279_p1;
wire   [12:0] tmp_17_cast_fu_1282_p1;
wire   [12:0] r_V_1_fu_1286_p2;
wire   [3:0] phitmp714_i_fu_1292_p4;
wire   [3:0] zbin1tmp_V_fu_1312_p2;
wire   [2:0] tmp_16_fu_1302_p4;
wire   [0:0] tmp_35_fu_1334_p3;
wire   [2:0] tmp_19_fu_1342_p2;
wire   [11:0] tmp_61_fu_1369_p1;
wire   [11:0] tmp_62_fu_1373_p2;
wire   [7:0] tmp_63_fu_1383_p1;
wire   [3:0] zbin2tmp_V_fu_1424_p2;
wire   [2:0] tmp_18_fu_1415_p4;
wire   [0:0] tmp_37_fu_1429_p3;
wire   [2:0] tmp_20_fu_1437_p2;
wire   [2:0] zbin2_V_fu_1443_p3;
wire   [3:0] tmp_21_fu_1456_p3;
wire   [0:0] op2_assign_fu_1451_p2;
wire   [3:0] finez_V_fu_1463_p2;
wire   [4:0] rinv_V_fu_1468_p2;
wire   [9:0] tmp_58_fu_1504_p1;
wire   [9:0] tmp_59_fu_1508_p2;
wire   [7:0] tmp_60_fu_1518_p1;
wire   [9:0] tmp_54_fu_1553_p1;
wire   [9:0] tmp_55_fu_1557_p2;
wire   [7:0] tmp_57_fu_1567_p1;
wire   [9:0] tmp_50_fu_1602_p1;
wire   [9:0] tmp_51_fu_1606_p2;
wire   [7:0] tmp_52_fu_1616_p1;
wire   [9:0] tmp_48_fu_1651_p1;
wire   [9:0] tmp_39_fu_1655_p2;
wire   [7:0] tmp_49_fu_1665_p1;
wire   [9:0] tmp_46_fu_1700_p1;
wire   [9:0] tmp_36_fu_1704_p2;
wire   [7:0] tmp_47_fu_1714_p1;
wire   [9:0] tmp_44_fu_1749_p1;
wire   [9:0] tmp_34_fu_1753_p2;
wire   [7:0] tmp_45_fu_1763_p1;
wire   [9:0] tmp_42_fu_1798_p1;
wire   [9:0] tmp_33_fu_1802_p2;
wire   [7:0] tmp_43_fu_1812_p1;
wire   [9:0] tmp_40_fu_1847_p1;
wire   [9:0] tmp_32_fu_1851_p2;
wire   [7:0] tmp_41_fu_1861_p1;
wire    ap_CS_fsm_state8;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1359;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

ProjectionRouterTop5_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
ProjectionRouterTop5_mux_53_8_1_1_U1(
    .din0(numbersin_0_V_reg_2001),
    .din1(numbersin_1_V_reg_2012),
    .din2(numbersin_2_V_reg_2022),
    .din3(numbersin_3_V_reg_2032),
    .din4(numbersin_4_V_reg_2038),
    .din5(tmp_10_fu_1064_p6),
    .dout(tmp_10_fu_1064_p7)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_1_fu_288 <= nvmprojout2_fu_1827_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_1_fu_288 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd2) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_2_fu_284 <= nvmprojout3_fu_1778_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_2_fu_284 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd3) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_3_fu_280 <= nvmprojout4_fu_1729_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_3_fu_280 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd4) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_4_fu_276 <= nvmprojout5_fu_1680_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_4_fu_276 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd5) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_5_fu_272 <= nvmprojout6_fu_1631_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_5_fu_272 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd6) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_6_fu_268 <= nvmprojout7_fu_1582_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_6_fu_268 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd7) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_7_fu_264 <= nvmprojout8_fu_1533_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_7_fu_264 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_8_fu_296 <= nallproj_fu_1404_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_8_fu_296 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd0) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        addr_index_assign_fu_292 <= nvmprojout1_fu_1876_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_fu_292 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Repl2_3_reg_755 <= 7'd0;
    end else if (((tmp_8_reg_2043 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Repl2_3_reg_755 <= i_reg_2047;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_fu_1009_p2 == 1'd0) & (tmp_8_fu_994_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_4_fu_300 <= mem_hasdata_V_4_fu_1103_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_4_fu_300 <= p_Val2_4_ph_fu_981_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_fu_1009_p2 == 1'd0) & (tmp_8_fu_994_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_addr_V_read_assign_fu_304 <= mem_read_addr_V_1_fu_1095_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_addr_V_read_assign_fu_304 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_2047 <= i_fu_1000_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2052_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        iphi_V_reg_2124 <= {{p_Val2_5_fu_1180_p3[43:41]}};
        p_Val2_5_reg_2119 <= p_Val2_5_fu_1180_p3;
        phitmp708_i_reg_2138 <= {{irinv_tmp_V_fu_1235_p2[10:6]}};
        phitmp718_i_reg_2133 <= {{p_Val2_5_fu_1180_p3[29:26]}};
        psseed_reg_2143 <= psseed_fu_1273_p2;
        tmp_14_reg_2128 <= {{p_Val2_5_fu_1180_p3[31:27]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        iphi_V_reg_2124_pp0_iter3_reg <= iphi_V_reg_2124;
        p_Repl2_3_reg_755_pp0_iter2_reg <= p_Repl2_3_reg_755_pp0_iter1_reg;
        p_Repl2_3_reg_755_pp0_iter3_reg <= p_Repl2_3_reg_755_pp0_iter2_reg;
        phitmp708_i_reg_2138_pp0_iter3_reg <= phitmp708_i_reg_2138;
        phitmp718_i_reg_2133_pp0_iter3_reg <= phitmp718_i_reg_2133;
        psseed_reg_2143_pp0_iter3_reg <= psseed_reg_2143;
        tmp_9_reg_2052_pp0_iter2_reg <= tmp_9_reg_2052_pp0_iter1_reg;
        tmp_9_reg_2052_pp0_iter3_reg <= tmp_9_reg_2052_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        numbersin_0_V_reg_2001 <= numbersin_0_V_fu_795_p3;
        numbersin_1_V_reg_2012 <= numbersin_1_V_fu_809_p3;
        numbersin_2_V_reg_2022 <= numbersin_2_V_fu_823_p3;
        numbersin_3_V_reg_2032 <= numbersin_3_V_fu_837_p3;
        p_Val2_s_reg_2006 <= p_Val2_s_fu_803_p2;
        tmp_15_cast_reg_1903[7] <= tmp_15_cast_fu_791_p1[7];
        tmp_2_cast_reg_1892[9 : 7] <= tmp_2_cast_fu_775_p1[9 : 7];
        tmp_2_reg_1897 <= tmp_2_fu_779_p1;
        tmp_4_reg_2017 <= tmp_4_fu_817_p2;
        tmp_5_reg_2027 <= tmp_5_fu_831_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        numbersin_4_V_reg_2038 <= numbersin_4_V_fu_958_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Repl2_3_reg_755_pp0_iter1_reg <= p_Repl2_3_reg_755;
        tmp_8_reg_2043 <= tmp_8_fu_994_p2;
        tmp_9_reg_2052_pp0_iter1_reg <= tmp_9_reg_2052;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        phitmp716_i_reg_2153 <= {{r_V_2_fu_1318_p2[5:2]}};
        r_V_2_reg_2148 <= r_V_2_fu_1318_p2;
        tmp_38_reg_2164 <= tmp_38_fu_1356_p1;
        zbin1_V_reg_2158 <= zbin1_V_fu_1348_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_fu_1009_p2 == 1'd0) & (tmp_8_fu_994_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_imem_V_reg_2056 <= read_imem_V_fu_1030_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_8_fu_994_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_9_reg_2052 <= tmp_9_fu_1009_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_2052 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_i1_i_i_i_reg_2109 <= tmp_i1_i_i_i_fu_1142_p2;
        tmp_i1_i_i_reg_2104 <= tmp_i1_i_i_fu_1137_p2;
        tmp_i1_i_reg_2099 <= tmp_i1_i_fu_1132_p2;
        tmp_i2_i_reg_2114 <= tmp_i2_i_fu_1147_p2;
        tmp_i_reg_2094 <= tmp_i_fu_1127_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        allprojout_dataarray_data_V_ce0 = 1'b1;
    end else begin
        allprojout_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        allprojout_dataarray_data_V_we0 = 1'b1;
    end else begin
        allprojout_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd0)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_0_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_0_V = 8'd0;
        end else begin
            allprojout_nentries_0_V = 'bx;
        end
    end else begin
        allprojout_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((bx_V_read_read_fu_308_p2 == 3'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd0) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_0_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd1)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_1_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_1_V = 8'd0;
        end else begin
            allprojout_nentries_1_V = 'bx;
        end
    end else begin
        allprojout_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_1_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd2)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_2_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_2_V = 8'd0;
        end else begin
            allprojout_nentries_2_V = 'bx;
        end
    end else begin
        allprojout_nentries_2_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd2) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_2_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd3)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_3_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_3_V = 8'd0;
        end else begin
            allprojout_nentries_3_V = 'bx;
        end
    end else begin
        allprojout_nentries_3_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd3) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_3_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd4)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_4_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_4_V = 8'd0;
        end else begin
            allprojout_nentries_4_V = 'bx;
        end
    end else begin
        allprojout_nentries_4_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd4) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_4_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd5)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_5_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_5_V = 8'd0;
        end else begin
            allprojout_nentries_5_V = 'bx;
        end
    end else begin
        allprojout_nentries_5_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd5) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_5_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_5_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd6)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_6_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_6_V = 8'd0;
        end else begin
            allprojout_nentries_6_V = 'bx;
        end
    end else begin
        allprojout_nentries_6_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd6) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_6_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_6_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_308_p2 == 3'd7)) begin
        if ((1'b1 == ap_condition_1359)) begin
            allprojout_nentries_7_V = p_09_0_i76_i_fu_1387_p2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            allprojout_nentries_7_V = 8'd0;
        end else begin
            allprojout_nentries_7_V = 'bx;
        end
    end else begin
        allprojout_nentries_7_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (bx_V_read_read_fu_308_p2 == 3'd7) & (1'b1 == ap_CS_fsm_state1)))) begin
        allprojout_nentries_7_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_7_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_8_fu_994_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_8_reg_2043 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_Repl2_3_phi_fu_759_p4 = i_reg_2047;
    end else begin
        ap_phi_mux_p_Repl2_3_phi_fu_759_p4 = p_Repl2_3_reg_755;
    end
end

always @ (*) begin
    if (((bx_o_V_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_56_fu_1121_p2 == 1'd1) & (tmp_8_fu_994_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj1in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj1in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj2in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj2in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj3in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj3in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj4in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj4in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj5in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj5in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd0) & (tmp_24_fu_1841_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout1_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (tmp_24_fu_1841_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout1_nentries_0_V = p_09_0_i_i_fu_1865_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout1_nentries_0_V = 8'd0;
    end else begin
        vmprojout1_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((iphi_V_reg_2124_pp0_iter3_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (tmp_24_fu_1841_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout1_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout1_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((iphi_V_reg_2124_pp0_iter3_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (tmp_24_fu_1841_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout1_nentries_1_V = p_09_0_i_i_fu_1865_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout1_nentries_1_V = 8'd0;
    end else begin
        vmprojout1_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((iphi_V_reg_2124_pp0_iter3_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (tmp_24_fu_1841_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout1_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout1_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_25_fu_1792_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout2_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_25_fu_1792_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout2_nentries_0_V = p_09_0_i35_i_fu_1816_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout2_nentries_0_V = 8'd0;
    end else begin
        vmprojout2_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_25_fu_1792_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout2_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout2_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_25_fu_1792_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout2_nentries_1_V = p_09_0_i35_i_fu_1816_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout2_nentries_1_V = 8'd0;
    end else begin
        vmprojout2_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_25_fu_1792_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd1) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout2_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout2_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_26_fu_1743_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd2) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout3_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_26_fu_1743_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd2) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout3_nentries_0_V = p_09_0_i41_i_fu_1767_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout3_nentries_0_V = 8'd0;
    end else begin
        vmprojout3_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_26_fu_1743_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd2) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout3_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout3_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_26_fu_1743_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd2) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout3_nentries_1_V = p_09_0_i41_i_fu_1767_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout3_nentries_1_V = 8'd0;
    end else begin
        vmprojout3_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_26_fu_1743_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd2) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout3_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout3_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout4_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout4_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_27_fu_1694_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd3) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout4_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout4_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_27_fu_1694_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd3) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout4_nentries_0_V = p_09_0_i47_i_fu_1718_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout4_nentries_0_V = 8'd0;
    end else begin
        vmprojout4_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_27_fu_1694_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd3) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout4_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout4_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_27_fu_1694_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd3) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout4_nentries_1_V = p_09_0_i47_i_fu_1718_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout4_nentries_1_V = 8'd0;
    end else begin
        vmprojout4_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_27_fu_1694_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd3) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout4_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout4_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout5_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout5_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_28_fu_1645_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd4) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout5_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout5_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_28_fu_1645_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd4) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout5_nentries_0_V = p_09_0_i53_i_fu_1669_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout5_nentries_0_V = 8'd0;
    end else begin
        vmprojout5_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_28_fu_1645_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd4) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout5_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout5_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_28_fu_1645_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd4) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout5_nentries_1_V = p_09_0_i53_i_fu_1669_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout5_nentries_1_V = 8'd0;
    end else begin
        vmprojout5_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_28_fu_1645_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd4) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout5_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout5_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout6_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout6_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_29_fu_1596_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd5) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout6_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout6_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_29_fu_1596_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd5) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout6_nentries_0_V = p_09_0_i59_i_fu_1620_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout6_nentries_0_V = 8'd0;
    end else begin
        vmprojout6_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_29_fu_1596_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd5) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout6_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout6_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_29_fu_1596_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd5) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout6_nentries_1_V = p_09_0_i59_i_fu_1620_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout6_nentries_1_V = 8'd0;
    end else begin
        vmprojout6_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_29_fu_1596_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd5) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout6_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout6_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout7_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout7_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_30_fu_1547_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd6) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout7_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout7_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_30_fu_1547_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd6) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout7_nentries_0_V = p_09_0_i65_i_fu_1571_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout7_nentries_0_V = 8'd0;
    end else begin
        vmprojout7_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_30_fu_1547_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd6) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout7_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout7_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_30_fu_1547_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd6) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout7_nentries_1_V = p_09_0_i65_i_fu_1571_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout7_nentries_1_V = 8'd0;
    end else begin
        vmprojout7_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_30_fu_1547_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd6) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout7_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout7_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout8_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout8_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_31_fu_1498_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd7) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout8_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout8_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_31_fu_1498_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd7) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout8_nentries_0_V = p_09_0_i71_i_fu_1522_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout8_nentries_0_V = 8'd0;
    end else begin
        vmprojout8_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_31_fu_1498_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd7) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd0)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd0) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout8_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout8_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_31_fu_1498_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd7) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout8_nentries_1_V = p_09_0_i71_i_fu_1522_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6))))) begin
        vmprojout8_nentries_1_V = 8'd0;
    end else begin
        vmprojout8_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_01001) & (tmp_31_fu_1498_p2 == 1'd1) & (iphi_V_reg_2124_pp0_iter3_reg == 3'd7) & (tmp_9_reg_2052_pp0_iter3_reg == 1'd0) & (tmp_2_reg_1897 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd7)) | ((bx_V_read_read_fu_308_p2 == 3'd0) & (tmp_2_fu_779_p1 == 1'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd1)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd2)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd3)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd4)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd5)) | ((tmp_2_fu_779_p1 == 1'd1) & (bx_V_read_read_fu_308_p2 == 3'd6)))))) begin
        vmprojout8_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout8_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (tmp_8_fu_994_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (tmp_8_fu_994_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((bx_o_V_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign allprojout_dataarray_data_V_address0 = tmp_63_cast_fu_1378_p1;

assign allprojout_dataarray_data_V_d0 = p_Val2_5_reg_2119;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1359 = ((1'b0 == ap_block_pp0_stage0_01001) & (tmp_53_fu_1363_p2 == 1'd1) & (tmp_9_reg_2052_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bx_V_read_read_fu_308_p2 = bx_V;

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign data_data_V_read_assign_1_fu_1159_p3 = ((tmp_i1_i_reg_2099[0:0] === 1'b1) ? proj2in_dataarray_data_V_q0 : data_data_V_read_assign_fu_1152_p3);

assign data_data_V_read_assign_2_fu_1166_p3 = ((tmp_i1_i_i_reg_2104[0:0] === 1'b1) ? proj3in_dataarray_data_V_q0 : data_data_V_read_assign_1_fu_1159_p3);

assign data_data_V_read_assign_3_fu_1173_p3 = ((tmp_i1_i_i_i_reg_2109[0:0] === 1'b1) ? proj4in_dataarray_data_V_q0 : data_data_V_read_assign_2_fu_1166_p3);

assign data_data_V_read_assign_fu_1152_p3 = ((tmp_i_reg_2094[0:0] === 1'b1) ? proj1in_dataarray_data_V_q0 : 60'd0);

assign finez_V_fu_1463_p2 = (phitmp718_i_reg_2133_pp0_iter3_reg - tmp_21_fu_1456_p3);

assign i_assign_fu_1081_p1 = read_imem_V_fu_1030_p1;

assign i_fu_1000_p2 = (ap_phi_mux_p_Repl2_3_phi_fu_759_p4 + 7'd1);

assign irinv_tmp_V_fu_1235_p2 = (11'd0 - p_shl_fu_1227_p3);

assign iseed_V_fu_1251_p4 = {{p_Val2_5_fu_1180_p3[59:57]}};

assign mem_hasdata_V_4_fu_1103_p3 = ((tmp_11_fu_1075_p2[0:0] === 1'b1) ? p_Val2_4_fu_300 : p_Result_3_fu_1085_p4);

assign mem_read_addr_V_1_fu_1095_p3 = ((tmp_11_fu_1075_p2[0:0] === 1'b1) ? mem_read_addr_V_fu_1050_p2 : 7'd0);

assign mem_read_addr_V_fu_1050_p2 = (7'd1 + read_addr_V_read_assign_fu_304);

assign nallproj_fu_1404_p2 = (addr_index_assign_8_fu_296 + 32'd1);

assign not_i_fu_1267_p2 = ((iseed_V_fu_1251_p4 != 3'd1) ? 1'b1 : 1'b0);

assign numbersin_0_V_fu_795_p3 = ((tmp_2_fu_779_p1[0:0] === 1'b1) ? proj1in_nentries_1_V : proj1in_nentries_0_V);

assign numbersin_1_V_fu_809_p3 = ((tmp_2_fu_779_p1[0:0] === 1'b1) ? proj2in_nentries_1_V : proj2in_nentries_0_V);

assign numbersin_2_V_fu_823_p3 = ((tmp_2_fu_779_p1[0:0] === 1'b1) ? proj3in_nentries_1_V : proj3in_nentries_0_V);

assign numbersin_3_V_fu_837_p3 = ((tmp_2_fu_779_p1[0:0] === 1'b1) ? proj4in_nentries_1_V : proj4in_nentries_0_V);

assign numbersin_4_V_fu_958_p3 = ((tmp_2_reg_1897[0:0] === 1'b1) ? proj5in_nentries_1_V : proj5in_nentries_0_V);

assign nvmprojout1_fu_1876_p2 = (addr_index_assign_fu_292 + 32'd1);

assign nvmprojout2_fu_1827_p2 = (addr_index_assign_1_fu_288 + 32'd1);

assign nvmprojout3_fu_1778_p2 = (addr_index_assign_2_fu_284 + 32'd1);

assign nvmprojout4_fu_1729_p2 = (addr_index_assign_3_fu_280 + 32'd1);

assign nvmprojout5_fu_1680_p2 = (addr_index_assign_4_fu_276 + 32'd1);

assign nvmprojout6_fu_1631_p2 = (addr_index_assign_5_fu_272 + 32'd1);

assign nvmprojout7_fu_1582_p2 = (addr_index_assign_6_fu_268 + 32'd1);

assign nvmprojout8_fu_1533_p2 = (addr_index_assign_7_fu_264 + 32'd1);

assign op2_assign_fu_1451_p2 = ((zbin2_V_fu_1443_p3 != zbin1_V_reg_2158) ? 1'b1 : 1'b0);

assign p_09_0_i35_i_fu_1816_p2 = (8'd1 + tmp_43_fu_1812_p1);

assign p_09_0_i41_i_fu_1767_p2 = (8'd1 + tmp_45_fu_1763_p1);

assign p_09_0_i47_i_fu_1718_p2 = (8'd1 + tmp_47_fu_1714_p1);

assign p_09_0_i53_i_fu_1669_p2 = (8'd1 + tmp_49_fu_1665_p1);

assign p_09_0_i59_i_fu_1620_p2 = (8'd1 + tmp_52_fu_1616_p1);

assign p_09_0_i65_i_fu_1571_p2 = (8'd1 + tmp_57_fu_1567_p1);

assign p_09_0_i71_i_fu_1522_p2 = (8'd1 + tmp_60_fu_1518_p1);

assign p_09_0_i76_i_fu_1387_p2 = (8'd1 + tmp_63_fu_1383_p1);

assign p_09_0_i_i_fu_1865_p2 = (8'd1 + tmp_41_fu_1861_p1);

always @ (*) begin
    p_Result_1_fu_940_p4 = p_Val2_2_fu_928_p3;
    p_Result_1_fu_940_p4[32'd3] = |(1'd1);
end

always @ (*) begin
    p_Result_2_fu_971_p4 = p_Val2_3_fu_950_p3;
    p_Result_2_fu_971_p4[32'd4] = |(1'd1);
end

always @ (*) begin
    p_Result_3_fu_1085_p4 = p_Val2_4_fu_300;
    p_Result_3_fu_1085_p4[i_assign_fu_1081_p1] = |(32'd0);
end

assign p_Result_s_fu_924_p1 = tmp_13_fu_916_p3;

assign p_Val2_1_cast_fu_912_p1 = p_Val2_1_fu_905_p3;

assign p_Val2_1_fu_905_p3 = ((tmp_4_reg_2017[0:0] === 1'b1) ? p_Val2_cast_cast_fu_895_p1 : tmp_3_fu_898_p3);

assign p_Val2_2_fu_928_p3 = ((tmp_5_reg_2027[0:0] === 1'b1) ? p_Val2_1_cast_fu_912_p1 : p_Result_s_fu_924_p1);

assign p_Val2_3_fu_950_p3 = ((tmp_6_fu_935_p2[0:0] === 1'b1) ? p_Val2_2_fu_928_p3 : p_Result_1_fu_940_p4);

assign p_Val2_4_ph_fu_981_p3 = ((tmp_7_fu_965_p2[0:0] === 1'b1) ? p_Val2_3_fu_950_p3 : p_Result_2_fu_971_p4);

assign p_Val2_5_fu_1180_p3 = ((tmp_i2_i_reg_2114[0:0] === 1'b1) ? proj5in_dataarray_data_V_q0 : data_data_V_read_assign_3_fu_1173_p3);

assign p_Val2_cast_cast_fu_895_p1 = p_Val2_s_reg_2006;

assign p_Val2_s_fu_803_p2 = ((numbersin_0_V_fu_795_p3 != 8'd0) ? 1'b1 : 1'b0);

assign p_shl_fu_1227_p3 = {{tmp_22_fu_1217_p4}, {1'd0}};

assign phitmp712_i_fu_1261_p2 = ((iseed_V_fu_1251_p4 != 3'd2) ? 1'b1 : 1'b0);

assign phitmp714_i_fu_1292_p4 = {{r_V_1_fu_1286_p2[5:2]}};

assign proj1in_dataarray_data_V_address0 = tmp_17_fu_1041_p1;

assign proj2in_dataarray_data_V_address0 = tmp_17_fu_1041_p1;

assign proj3in_dataarray_data_V_address0 = tmp_17_fu_1041_p1;

assign proj4in_dataarray_data_V_address0 = tmp_17_fu_1041_p1;

assign proj5in_dataarray_data_V_address0 = tmp_17_fu_1041_p1;

assign psseed_fu_1273_p2 = (phitmp712_i_fu_1261_p2 & not_i_fu_1267_p2);

assign r_V_1_fu_1286_p2 = (13'd62 + tmp_17_cast_fu_1282_p1);

assign r_V_2_fu_1318_p2 = (13'd2 + tmp_17_cast_fu_1282_p1);

assign r_V_fu_1279_p1 = $signed(tmp_14_reg_2128);

assign read_imem_V_fu_1030_p1 = val_assign_fu_1022_p3[4:0];

assign ret_V_fu_1473_p7 = {{{{{{p_Repl2_3_reg_755_pp0_iter3_reg}, {zbin1_V_reg_2158}}, {op2_assign_fu_1451_p2}}, {finez_V_fu_1463_p2}}, {rinv_V_fu_1468_p2}}, {psseed_reg_2143_pp0_iter3_reg}};

assign rinv_V_fu_1468_p2 = (phitmp708_i_reg_2138_pp0_iter3_reg ^ 5'd16);

assign tmp_10_fu_1064_p6 = val_assign_fu_1022_p3[2:0];

assign tmp_11_cast_fu_1056_p1 = mem_read_addr_V_fu_1050_p2;

assign tmp_11_fu_1075_p2 = ((tmp_11_cast_fu_1056_p1 < tmp_10_fu_1064_p7) ? 1'b1 : 1'b0);

assign tmp_12_fu_783_p3 = {{tmp_2_fu_779_p1}, {7'd0}};

assign tmp_13_fu_916_p3 = {{1'd1}, {p_Val2_1_fu_905_p3}};

assign tmp_15_cast_fu_791_p1 = tmp_12_fu_783_p3;

assign tmp_15_fu_1034_p3 = {{tmp_2_reg_1897}, {read_addr_V_read_assign_fu_304}};

assign tmp_16_fu_1302_p4 = {{r_V_1_fu_1286_p2[4:2]}};

assign tmp_17_cast_fu_1282_p1 = $unsigned(r_V_fu_1279_p1);

assign tmp_17_fu_1041_p1 = tmp_15_fu_1034_p3;

assign tmp_18_fu_1415_p4 = {{r_V_2_reg_2148[4:2]}};

assign tmp_19_fu_1342_p2 = (tmp_16_fu_1302_p4 ^ 3'd4);

assign tmp_20_fu_1437_p2 = (tmp_18_fu_1415_p4 ^ 3'd4);

assign tmp_21_fu_1456_p3 = {{tmp_38_reg_2164}, {3'd0}};

assign tmp_22_fu_1217_p4 = {{p_Val2_5_fu_1180_p3[19:10]}};

assign tmp_24_fu_1841_p2 = (($signed(addr_index_assign_fu_292) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_25_fu_1792_p2 = (($signed(addr_index_assign_1_fu_288) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_26_fu_1743_p2 = (($signed(addr_index_assign_2_fu_284) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_27_fu_1694_p2 = (($signed(addr_index_assign_3_fu_280) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_28_fu_1645_p2 = (($signed(addr_index_assign_4_fu_276) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_29_fu_1596_p2 = (($signed(addr_index_assign_5_fu_272) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_2_cast_fu_775_p1 = tmp_fu_767_p3;

assign tmp_2_fu_779_p1 = bx_V[0:0];

assign tmp_30_fu_1547_p2 = (($signed(addr_index_assign_6_fu_268) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_31_fu_1498_p2 = (($signed(addr_index_assign_7_fu_264) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_32_fu_1851_p2 = (tmp_40_fu_1847_p1 + tmp_15_cast_reg_1903);

assign tmp_33_fu_1802_p2 = (tmp_42_fu_1798_p1 + tmp_15_cast_reg_1903);

assign tmp_34_fu_1753_p2 = (tmp_44_fu_1749_p1 + tmp_15_cast_reg_1903);

assign tmp_35_fu_1334_p3 = zbin1tmp_V_fu_1312_p2[32'd3];

assign tmp_36_cast_fu_1856_p1 = $signed(tmp_32_fu_1851_p2);

assign tmp_36_fu_1704_p2 = (tmp_46_fu_1700_p1 + tmp_15_cast_reg_1903);

assign tmp_37_fu_1429_p3 = zbin2tmp_V_fu_1424_p2[32'd3];

assign tmp_38_fu_1356_p1 = zbin1_V_fu_1348_p3[0:0];

assign tmp_39_cast_fu_1807_p1 = $signed(tmp_33_fu_1802_p2);

assign tmp_39_fu_1655_p2 = (tmp_48_fu_1651_p1 + tmp_15_cast_reg_1903);

assign tmp_3_fu_898_p3 = {{1'd1}, {p_Val2_s_reg_2006}};

assign tmp_40_fu_1847_p1 = addr_index_assign_fu_292[9:0];

assign tmp_41_fu_1861_p1 = addr_index_assign_fu_292[7:0];

assign tmp_42_fu_1798_p1 = addr_index_assign_1_fu_288[9:0];

assign tmp_43_fu_1812_p1 = addr_index_assign_1_fu_288[7:0];

assign tmp_44_fu_1749_p1 = addr_index_assign_2_fu_284[9:0];

assign tmp_45_fu_1763_p1 = addr_index_assign_2_fu_284[7:0];

assign tmp_46_fu_1700_p1 = addr_index_assign_3_fu_280[9:0];

assign tmp_47_fu_1714_p1 = addr_index_assign_3_fu_280[7:0];

assign tmp_48_fu_1651_p1 = addr_index_assign_4_fu_276[9:0];

assign tmp_49_fu_1665_p1 = addr_index_assign_4_fu_276[7:0];

assign tmp_4_fu_817_p2 = ((numbersin_1_V_fu_809_p3 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_50_fu_1602_p1 = addr_index_assign_5_fu_272[9:0];

assign tmp_51_fu_1606_p2 = (tmp_50_fu_1602_p1 + tmp_15_cast_reg_1903);

assign tmp_52_fu_1616_p1 = addr_index_assign_5_fu_272[7:0];

assign tmp_53_fu_1363_p2 = (($signed(addr_index_assign_8_fu_296) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_54_fu_1553_p1 = addr_index_assign_6_fu_268[9:0];

assign tmp_55_fu_1557_p2 = (tmp_54_fu_1553_p1 + tmp_15_cast_reg_1903);

assign tmp_56_fu_1121_p2 = ((ap_phi_mux_p_Repl2_3_phi_fu_759_p4 == 7'd101) ? 1'b1 : 1'b0);

assign tmp_57_cast_fu_1758_p1 = $signed(tmp_34_fu_1753_p2);

assign tmp_57_fu_1567_p1 = addr_index_assign_6_fu_268[7:0];

assign tmp_58_cast_fu_1709_p1 = $signed(tmp_36_fu_1704_p2);

assign tmp_58_fu_1504_p1 = addr_index_assign_7_fu_264[9:0];

assign tmp_59_cast_fu_1660_p1 = $signed(tmp_39_fu_1655_p2);

assign tmp_59_fu_1508_p2 = (tmp_58_fu_1504_p1 + tmp_15_cast_reg_1903);

assign tmp_5_fu_831_p2 = ((numbersin_2_V_fu_823_p3 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_60_cast_fu_1611_p1 = $signed(tmp_51_fu_1606_p2);

assign tmp_60_fu_1518_p1 = addr_index_assign_7_fu_264[7:0];

assign tmp_61_cast_fu_1562_p1 = $signed(tmp_55_fu_1557_p2);

assign tmp_61_fu_1369_p1 = addr_index_assign_8_fu_296[11:0];

assign tmp_62_cast_fu_1513_p1 = $signed(tmp_59_fu_1508_p2);

assign tmp_62_fu_1373_p2 = (tmp_61_fu_1369_p1 + tmp_2_cast_reg_1892);

assign tmp_63_cast_fu_1378_p1 = $signed(tmp_62_fu_1373_p2);

assign tmp_63_fu_1383_p1 = addr_index_assign_8_fu_296[7:0];

assign tmp_6_fu_935_p2 = ((numbersin_3_V_reg_2032 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_7_fu_965_p2 = ((numbersin_4_V_fu_958_p3 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_994_p2 = ((ap_phi_mux_p_Repl2_3_phi_fu_759_p4 == 7'd102) ? 1'b1 : 1'b0);

assign tmp_9_fu_1009_p2 = ((p_Val2_4_fu_300 == 5'd0) ? 1'b1 : 1'b0);

assign tmp_fu_767_p3 = {{bx_V}, {7'd0}};

assign tmp_i1_i_fu_1132_p2 = ((read_imem_V_reg_2056 == 5'd1) ? 1'b1 : 1'b0);

assign tmp_i1_i_i_fu_1137_p2 = ((read_imem_V_reg_2056 == 5'd2) ? 1'b1 : 1'b0);

assign tmp_i1_i_i_i_fu_1142_p2 = ((read_imem_V_reg_2056 == 5'd3) ? 1'b1 : 1'b0);

assign tmp_i2_i_fu_1147_p2 = ((read_imem_V_reg_2056 == 5'd4) ? 1'b1 : 1'b0);

assign tmp_i_fu_1127_p2 = ((read_imem_V_reg_2056 == 5'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_1018_p1 = p_Val2_4_fu_300;


always @ (tmp_s_fu_1018_p1) begin
    if (tmp_s_fu_1018_p1[0] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd0;
    end else if (tmp_s_fu_1018_p1[1] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd1;
    end else if (tmp_s_fu_1018_p1[2] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd2;
    end else if (tmp_s_fu_1018_p1[3] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd3;
    end else if (tmp_s_fu_1018_p1[4] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd4;
    end else if (tmp_s_fu_1018_p1[5] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd5;
    end else if (tmp_s_fu_1018_p1[6] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd6;
    end else if (tmp_s_fu_1018_p1[7] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd7;
    end else if (tmp_s_fu_1018_p1[8] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd8;
    end else if (tmp_s_fu_1018_p1[9] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd9;
    end else if (tmp_s_fu_1018_p1[10] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd10;
    end else if (tmp_s_fu_1018_p1[11] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd11;
    end else if (tmp_s_fu_1018_p1[12] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd12;
    end else if (tmp_s_fu_1018_p1[13] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd13;
    end else if (tmp_s_fu_1018_p1[14] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd14;
    end else if (tmp_s_fu_1018_p1[15] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd15;
    end else if (tmp_s_fu_1018_p1[16] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd16;
    end else if (tmp_s_fu_1018_p1[17] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd17;
    end else if (tmp_s_fu_1018_p1[18] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd18;
    end else if (tmp_s_fu_1018_p1[19] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd19;
    end else if (tmp_s_fu_1018_p1[20] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd20;
    end else if (tmp_s_fu_1018_p1[21] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd21;
    end else if (tmp_s_fu_1018_p1[22] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd22;
    end else if (tmp_s_fu_1018_p1[23] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd23;
    end else if (tmp_s_fu_1018_p1[24] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd24;
    end else if (tmp_s_fu_1018_p1[25] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd25;
    end else if (tmp_s_fu_1018_p1[26] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd26;
    end else if (tmp_s_fu_1018_p1[27] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd27;
    end else if (tmp_s_fu_1018_p1[28] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd28;
    end else if (tmp_s_fu_1018_p1[29] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd29;
    end else if (tmp_s_fu_1018_p1[30] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd30;
    end else if (tmp_s_fu_1018_p1[31] == 1'b1) begin
        val_assign_fu_1022_p3 = 32'd31;
    end else begin
        val_assign_fu_1022_p3 = 32'd32;
    end
end

assign vmprojout1_dataarray_data_V_address0 = tmp_36_cast_fu_1856_p1;

assign vmprojout1_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout2_dataarray_data_V_address0 = tmp_39_cast_fu_1807_p1;

assign vmprojout2_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout3_dataarray_data_V_address0 = tmp_57_cast_fu_1758_p1;

assign vmprojout3_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout4_dataarray_data_V_address0 = tmp_58_cast_fu_1709_p1;

assign vmprojout4_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout5_dataarray_data_V_address0 = tmp_59_cast_fu_1660_p1;

assign vmprojout5_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout6_dataarray_data_V_address0 = tmp_60_cast_fu_1611_p1;

assign vmprojout6_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout7_dataarray_data_V_address0 = tmp_61_cast_fu_1562_p1;

assign vmprojout7_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign vmprojout8_dataarray_data_V_address0 = tmp_62_cast_fu_1513_p1;

assign vmprojout8_dataarray_data_V_d0 = ret_V_fu_1473_p7;

assign zbin1_V_fu_1348_p3 = ((tmp_35_fu_1334_p3[0:0] === 1'b1) ? 3'd0 : tmp_19_fu_1342_p2);

assign zbin1tmp_V_fu_1312_p2 = (4'd4 + phitmp714_i_fu_1292_p4);

assign zbin2_V_fu_1443_p3 = ((tmp_37_fu_1429_p3[0:0] === 1'b1) ? 3'd7 : tmp_20_fu_1437_p2);

assign zbin2tmp_V_fu_1424_p2 = (4'd4 + phitmp716_i_reg_2153);

always @ (posedge ap_clk) begin
    tmp_2_cast_reg_1892[6:0] <= 7'b0000000;
    tmp_2_cast_reg_1892[11:10] <= 2'b00;
    tmp_15_cast_reg_1903[6:0] <= 7'b0000000;
    tmp_15_cast_reg_1903[9:8] <= 2'b00;
end

endmodule //ProjectionRouterTop5
