#================================================================================
#  Configure and add AXI slaves
#  Auto-generated by 
#================================================================================
#VIRTEX_SYS_MGMT
[AXI_IP_SYS_MGMT VIRTEX_SYS_MGMT         ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0x83c42000 4K 0]

#V_IO
[AXI_PL_DEV_CONNECT V_IO                 ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0x83c40000 4K]

