-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatchCalculatorTop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bx_V : IN STD_LOGIC_VECTOR (2 downto 0);
    match1_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match1_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match1_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match1_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match1_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match2_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match2_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match2_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match2_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match2_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match3_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match3_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match3_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match3_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match3_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match4_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match4_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match4_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match4_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match4_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match5_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match5_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match5_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match5_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match5_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match6_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match6_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match6_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match6_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match6_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match7_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match7_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match7_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match7_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match7_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match8_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    match8_dataarray_data_V_ce0 : OUT STD_LOGIC;
    match8_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
    match8_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    match8_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    allstub_dataarray_data_V_ce0 : OUT STD_LOGIC;
    allstub_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (35 downto 0);
    allstub_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_2_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_3_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_4_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_5_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_6_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allstub_nentries_7_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    allproj_dataarray_data_V_ce0 : OUT STD_LOGIC;
    allproj_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (59 downto 0);
    allproj_nentries_0_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_1_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_2_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_3_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_4_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_5_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_6_V : IN STD_LOGIC_VECTOR (7 downto 0);
    allproj_nentries_7_V : IN STD_LOGIC_VECTOR (7 downto 0);
    bx_o_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    bx_o_V_ap_vld : OUT STD_LOGIC;
    fullmatch1_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch1_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch1_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch1_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch1_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch1_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch1_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch1_nentries_1_V_ap_vld : OUT STD_LOGIC;
    fullmatch2_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch2_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch2_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch2_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch2_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch2_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch2_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch2_nentries_1_V_ap_vld : OUT STD_LOGIC;
    fullmatch3_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch3_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch3_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch3_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch3_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch3_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch3_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch3_nentries_1_V_ap_vld : OUT STD_LOGIC;
    fullmatch4_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch4_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch4_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch4_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch4_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch4_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch4_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch4_nentries_1_V_ap_vld : OUT STD_LOGIC;
    fullmatch5_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch5_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch5_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch5_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch5_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch5_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch5_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch5_nentries_1_V_ap_vld : OUT STD_LOGIC;
    fullmatch6_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch6_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch6_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch6_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch6_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch6_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch6_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch6_nentries_1_V_ap_vld : OUT STD_LOGIC;
    fullmatch7_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch7_dataarray_data_V_ce0 : OUT STD_LOGIC;
    fullmatch7_dataarray_data_V_we0 : OUT STD_LOGIC;
    fullmatch7_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
    fullmatch7_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch7_nentries_0_V_ap_vld : OUT STD_LOGIC;
    fullmatch7_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    fullmatch7_nentries_1_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of MatchCalculatorTop is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MatchCalculatorTop,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.652250,HLS_SYN_LAT=118,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=1704,HLS_SYN_LUT=6266,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bx_o_V_1_data_reg : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal bx_o_V_1_vld_reg : STD_LOGIC := '0';
    signal bx_o_V_1_vld_in : STD_LOGIC;
    signal bx_o_V_1_ack_in : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_ap_start : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_ap_done : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_ap_idle : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_ap_ready : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match1_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match1_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match2_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match2_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match3_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match3_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match4_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match4_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match5_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match5_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match6_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match6_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match7_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match7_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_match8_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_match8_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_allstub_dataarray_data_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_MatchCalculator_fu_260_allstub_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_allproj_dataarray_data_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_MatchCalculator_fu_260_allproj_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_bx_o_V : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_MatchCalculator_fu_260_bx_o_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_ce0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_we0 : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_d0 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V_ap_vld : STD_LOGIC;
    signal grp_MatchCalculator_fu_260_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);

    component MatchCalculator IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bx_V : IN STD_LOGIC_VECTOR (2 downto 0);
        match1_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match1_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match1_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match1_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match1_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match2_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match2_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match2_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match2_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match2_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match3_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match3_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match3_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match3_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match3_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match4_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match4_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match4_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match4_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match4_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match5_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match5_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match5_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match5_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match5_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match6_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match6_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match6_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match6_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match6_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match7_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match7_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match7_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match7_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match7_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match8_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        match8_dataarray_data_V_ce0 : OUT STD_LOGIC;
        match8_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        match8_nentries_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        match8_nentries_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
        allstub_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        allstub_dataarray_data_V_ce0 : OUT STD_LOGIC;
        allstub_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (35 downto 0);
        allproj_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        allproj_dataarray_data_V_ce0 : OUT STD_LOGIC;
        allproj_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (59 downto 0);
        bx_o_V : OUT STD_LOGIC_VECTOR (2 downto 0);
        bx_o_V_ap_vld : OUT STD_LOGIC;
        fullmatch1_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch1_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch1_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch1_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch1_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch1_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch1_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch1_nentries_1_V_ap_vld : OUT STD_LOGIC;
        fullmatch2_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch2_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch2_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch2_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch2_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch2_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch2_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch2_nentries_1_V_ap_vld : OUT STD_LOGIC;
        fullmatch3_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch3_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch3_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch3_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch3_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch3_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch3_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch3_nentries_1_V_ap_vld : OUT STD_LOGIC;
        fullmatch4_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch4_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch4_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch4_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch4_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch4_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch4_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch4_nentries_1_V_ap_vld : OUT STD_LOGIC;
        fullmatch5_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch5_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch5_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch5_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch5_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch5_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch5_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch5_nentries_1_V_ap_vld : OUT STD_LOGIC;
        fullmatch6_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch6_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch6_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch6_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch6_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch6_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch6_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch6_nentries_1_V_ap_vld : OUT STD_LOGIC;
        fullmatch7_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch7_dataarray_data_V_ce0 : OUT STD_LOGIC;
        fullmatch7_dataarray_data_V_we0 : OUT STD_LOGIC;
        fullmatch7_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (44 downto 0);
        fullmatch7_nentries_0_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch7_nentries_0_V_ap_vld : OUT STD_LOGIC;
        fullmatch7_nentries_1_V : OUT STD_LOGIC_VECTOR (7 downto 0);
        fullmatch7_nentries_1_V_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_MatchCalculator_fu_260 : component MatchCalculator
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MatchCalculator_fu_260_ap_start,
        ap_done => grp_MatchCalculator_fu_260_ap_done,
        ap_idle => grp_MatchCalculator_fu_260_ap_idle,
        ap_ready => grp_MatchCalculator_fu_260_ap_ready,
        bx_V => bx_V,
        match1_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match1_dataarray_data_V_address0,
        match1_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match1_dataarray_data_V_ce0,
        match1_dataarray_data_V_q0 => match1_dataarray_data_V_q0,
        match1_nentries_0_V_read => match1_nentries_0_V,
        match1_nentries_1_V_read => match1_nentries_1_V,
        match2_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match2_dataarray_data_V_address0,
        match2_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match2_dataarray_data_V_ce0,
        match2_dataarray_data_V_q0 => match2_dataarray_data_V_q0,
        match2_nentries_0_V_read => match2_nentries_0_V,
        match2_nentries_1_V_read => match2_nentries_1_V,
        match3_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match3_dataarray_data_V_address0,
        match3_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match3_dataarray_data_V_ce0,
        match3_dataarray_data_V_q0 => match3_dataarray_data_V_q0,
        match3_nentries_0_V_read => match3_nentries_0_V,
        match3_nentries_1_V_read => match3_nentries_1_V,
        match4_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match4_dataarray_data_V_address0,
        match4_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match4_dataarray_data_V_ce0,
        match4_dataarray_data_V_q0 => match4_dataarray_data_V_q0,
        match4_nentries_0_V_read => match4_nentries_0_V,
        match4_nentries_1_V_read => match4_nentries_1_V,
        match5_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match5_dataarray_data_V_address0,
        match5_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match5_dataarray_data_V_ce0,
        match5_dataarray_data_V_q0 => match5_dataarray_data_V_q0,
        match5_nentries_0_V_read => match5_nentries_0_V,
        match5_nentries_1_V_read => match5_nentries_1_V,
        match6_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match6_dataarray_data_V_address0,
        match6_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match6_dataarray_data_V_ce0,
        match6_dataarray_data_V_q0 => match6_dataarray_data_V_q0,
        match6_nentries_0_V_read => match6_nentries_0_V,
        match6_nentries_1_V_read => match6_nentries_1_V,
        match7_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match7_dataarray_data_V_address0,
        match7_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match7_dataarray_data_V_ce0,
        match7_dataarray_data_V_q0 => match7_dataarray_data_V_q0,
        match7_nentries_0_V_read => match7_nentries_0_V,
        match7_nentries_1_V_read => match7_nentries_1_V,
        match8_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_match8_dataarray_data_V_address0,
        match8_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_match8_dataarray_data_V_ce0,
        match8_dataarray_data_V_q0 => match8_dataarray_data_V_q0,
        match8_nentries_0_V_read => match8_nentries_0_V,
        match8_nentries_1_V_read => match8_nentries_1_V,
        allstub_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_allstub_dataarray_data_V_address0,
        allstub_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_allstub_dataarray_data_V_ce0,
        allstub_dataarray_data_V_q0 => allstub_dataarray_data_V_q0,
        allproj_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_allproj_dataarray_data_V_address0,
        allproj_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_allproj_dataarray_data_V_ce0,
        allproj_dataarray_data_V_q0 => allproj_dataarray_data_V_q0,
        bx_o_V => grp_MatchCalculator_fu_260_bx_o_V,
        bx_o_V_ap_vld => grp_MatchCalculator_fu_260_bx_o_V_ap_vld,
        fullmatch1_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_address0,
        fullmatch1_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_ce0,
        fullmatch1_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_we0,
        fullmatch1_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_d0,
        fullmatch1_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V,
        fullmatch1_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V_ap_vld,
        fullmatch1_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V,
        fullmatch1_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V_ap_vld,
        fullmatch2_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_address0,
        fullmatch2_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_ce0,
        fullmatch2_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_we0,
        fullmatch2_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_d0,
        fullmatch2_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V,
        fullmatch2_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V_ap_vld,
        fullmatch2_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V,
        fullmatch2_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V_ap_vld,
        fullmatch3_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_address0,
        fullmatch3_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_ce0,
        fullmatch3_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_we0,
        fullmatch3_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_d0,
        fullmatch3_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V,
        fullmatch3_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V_ap_vld,
        fullmatch3_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V,
        fullmatch3_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V_ap_vld,
        fullmatch4_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_address0,
        fullmatch4_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_ce0,
        fullmatch4_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_we0,
        fullmatch4_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_d0,
        fullmatch4_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V,
        fullmatch4_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V_ap_vld,
        fullmatch4_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V,
        fullmatch4_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V_ap_vld,
        fullmatch5_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_address0,
        fullmatch5_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_ce0,
        fullmatch5_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_we0,
        fullmatch5_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_d0,
        fullmatch5_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V,
        fullmatch5_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V_ap_vld,
        fullmatch5_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V,
        fullmatch5_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V_ap_vld,
        fullmatch6_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_address0,
        fullmatch6_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_ce0,
        fullmatch6_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_we0,
        fullmatch6_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_d0,
        fullmatch6_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V,
        fullmatch6_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V_ap_vld,
        fullmatch6_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V,
        fullmatch6_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V_ap_vld,
        fullmatch7_dataarray_data_V_address0 => grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_address0,
        fullmatch7_dataarray_data_V_ce0 => grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_ce0,
        fullmatch7_dataarray_data_V_we0 => grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_we0,
        fullmatch7_dataarray_data_V_d0 => grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_d0,
        fullmatch7_nentries_0_V => grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V,
        fullmatch7_nentries_0_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V_ap_vld,
        fullmatch7_nentries_1_V => grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V,
        fullmatch7_nentries_1_V_ap_vld => grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_MatchCalculator_fu_260_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MatchCalculator_fu_260_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_MatchCalculator_fu_260_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MatchCalculator_fu_260_ap_ready = ap_const_logic_1)) then 
                    grp_MatchCalculator_fu_260_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    bx_o_V_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (bx_o_V_1_vld_reg = ap_const_logic_0) and (bx_o_V_1_vld_in = ap_const_logic_1))) then 
                bx_o_V_1_vld_reg <= ap_const_logic_1;
            elsif (((bx_o_V_1_vld_in = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1) and (bx_o_V_1_vld_reg = ap_const_logic_1))) then 
                bx_o_V_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (bx_o_V_1_vld_reg = ap_const_logic_0) and (bx_o_V_1_vld_in = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (bx_o_V_1_vld_in = ap_const_logic_1) and (bx_o_V_1_vld_reg = ap_const_logic_1)))) then
                bx_o_V_1_data_reg <= grp_MatchCalculator_fu_260_bx_o_V;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, bx_o_V_1_ack_in, grp_MatchCalculator_fu_260_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_MatchCalculator_fu_260_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (bx_o_V_1_ack_in = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    allproj_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_allproj_dataarray_data_V_address0;
    allproj_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_allproj_dataarray_data_V_ce0;
    allstub_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_allstub_dataarray_data_V_address0;
    allstub_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_allstub_dataarray_data_V_ce0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(bx_o_V_1_ack_in, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (bx_o_V_1_ack_in = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(bx_o_V_1_ack_in, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (bx_o_V_1_ack_in = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bx_o_V <= bx_o_V_1_data_reg;

    bx_o_V_1_ack_in_assign_proc : process(bx_o_V_1_vld_reg)
    begin
        if (((bx_o_V_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (bx_o_V_1_vld_reg = ap_const_logic_1)))) then 
            bx_o_V_1_ack_in <= ap_const_logic_1;
        else 
            bx_o_V_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;

    bx_o_V_1_vld_in <= grp_MatchCalculator_fu_260_bx_o_V_ap_vld;
    bx_o_V_ap_vld <= bx_o_V_1_vld_reg;
    fullmatch1_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_address0;
    fullmatch1_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_ce0;
    fullmatch1_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_d0;
    fullmatch1_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_we0;
    fullmatch1_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V;
    fullmatch1_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V_ap_vld;
    fullmatch1_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V;
    fullmatch1_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V_ap_vld;
    fullmatch2_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_address0;
    fullmatch2_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_ce0;
    fullmatch2_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_d0;
    fullmatch2_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_we0;
    fullmatch2_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V;
    fullmatch2_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V_ap_vld;
    fullmatch2_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V;
    fullmatch2_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V_ap_vld;
    fullmatch3_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_address0;
    fullmatch3_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_ce0;
    fullmatch3_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_d0;
    fullmatch3_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_we0;
    fullmatch3_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V;
    fullmatch3_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V_ap_vld;
    fullmatch3_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V;
    fullmatch3_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V_ap_vld;
    fullmatch4_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_address0;
    fullmatch4_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_ce0;
    fullmatch4_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_d0;
    fullmatch4_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_we0;
    fullmatch4_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V;
    fullmatch4_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V_ap_vld;
    fullmatch4_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V;
    fullmatch4_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V_ap_vld;
    fullmatch5_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_address0;
    fullmatch5_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_ce0;
    fullmatch5_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_d0;
    fullmatch5_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_we0;
    fullmatch5_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V;
    fullmatch5_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V_ap_vld;
    fullmatch5_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V;
    fullmatch5_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V_ap_vld;
    fullmatch6_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_address0;
    fullmatch6_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_ce0;
    fullmatch6_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_d0;
    fullmatch6_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_we0;
    fullmatch6_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V;
    fullmatch6_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V_ap_vld;
    fullmatch6_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V;
    fullmatch6_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V_ap_vld;
    fullmatch7_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_address0;
    fullmatch7_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_ce0;
    fullmatch7_dataarray_data_V_d0 <= grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_d0;
    fullmatch7_dataarray_data_V_we0 <= grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_we0;
    fullmatch7_nentries_0_V <= grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V;
    fullmatch7_nentries_0_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V_ap_vld;
    fullmatch7_nentries_1_V <= grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V;
    fullmatch7_nentries_1_V_ap_vld <= grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V_ap_vld;
    grp_MatchCalculator_fu_260_ap_start <= grp_MatchCalculator_fu_260_ap_start_reg;
    match1_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match1_dataarray_data_V_address0;
    match1_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match1_dataarray_data_V_ce0;
    match2_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match2_dataarray_data_V_address0;
    match2_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match2_dataarray_data_V_ce0;
    match3_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match3_dataarray_data_V_address0;
    match3_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match3_dataarray_data_V_ce0;
    match4_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match4_dataarray_data_V_address0;
    match4_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match4_dataarray_data_V_ce0;
    match5_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match5_dataarray_data_V_address0;
    match5_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match5_dataarray_data_V_ce0;
    match6_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match6_dataarray_data_V_address0;
    match6_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match6_dataarray_data_V_ce0;
    match7_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match7_dataarray_data_V_address0;
    match7_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match7_dataarray_data_V_ce0;
    match8_dataarray_data_V_address0 <= grp_MatchCalculator_fu_260_match8_dataarray_data_V_address0;
    match8_dataarray_data_V_ce0 <= grp_MatchCalculator_fu_260_match8_dataarray_data_V_ce0;
end behav;
