# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/nfs/opt/Xilinx/Vivado/2018.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcvu7p-flvb2104-1-e ../xilinx_com_hls_ProjectionRouterTop_1_0.zip
